version: '3'

services:
  frontend:
    build: ./movie-project-mern
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./movie-mern-project-backend
    ports:
      - "3500:3500"
    environment:
      - DB_URL=mongodb+srv://root:root@librarydb.qys5kcl.mongodb.net/?retryWrites=true&w=majority&appName=librarydb
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: librarydb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
