services:
  frontend:
    build: ./movie-project-mern
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./movie-mern-project-backend
    ports:
      - "3500:3500"
    environment:
      - MONGO_URI=mongodb+srv://root:root@librarydb.qys5kcl.mongodb.net/?retryWrites=true&w=majority&appName=librarydb
