version: '3.8'
services:
  frontend:
    build: ./movie-project-mern
    ports:
      - "80:80"

  backend:
    build: ./movie-mern-project-backend
    ports:
      - "3500:3500"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://root:root@db:27017/mydb  

  db:
    build: ./db
    ports:
      - "27017:27017"
