version: '3.8'
services:
  frontend:
    build: ./movie-project-mern
    ports:
      - "3000:3000"

  backend:
    build: ./movie-mern-project-backend
    ports:
      - "3031:3031"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
