name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the frontend Docker image
      - name: Build frontend image
        run: docker build -t srimathi2004/movie-frontend:latest ./movie-project-mern # Update path if needed

      # Step 4: Build the backend Docker image
      - name: Build backend image
        run: docker build -t srimathi2004/movie-backend:latest ./movie-mern-project-backend

      # Step 5: List Docker images (optional, for debugging)
      - name: List Docker images
        run: docker images

      # Step 6: Push Docker images
      - name: Push frontend image
        run: docker push srimathi2004/movie-frontend:latest

      - name: Push backend image
        run: docker push srimathi2004/movie-backend:latest
