name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend image
        run: docker build -t frontend ./movie-project-mern

      - name: Build backend image
        run: docker build -t backend ./movie-mern-project-backend

      - name: Run tests for backend
        run: docker run backend npm test

      - name: Push Docker image (Optional)
        run: |
          echo "${{ secrets.Srimathi@#15 }}" | docker login -u ${{ secrets.srimathi2004 }} --password-stdin
           docker tag frontend srimathi2004/movie-frontend
          docker tag backend srimathi2004/movie-backend
          docker push srimathi2004/movie-frontend
          docker push srimathi2004/movie-backend
