name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build frontend image
      - name: Build frontend image
        run: docker build -t srimathi2004/movie-frontend:latest ./movie-project-mern

      # Verify frontend image
      - name: Verify frontend image
        run: docker images | grep srimathi2004/movie-frontend

      # Build backend image
      - name: Build backend image
        run: docker build -t srimathi2004/movie-backend:latest ./movie-mern-project-backend

      # Run backend tests (ensure tests are configured in package.json)
      - name: Run tests for backend
        run: docker run --rm srimathi2004/movie-backend:latest npm test

  push-to-registry:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push frontend image to Docker Hub
      - name: Push frontend image to Docker Hub
        run: docker push srimathi2004/movie-frontend:latest

      # Push backend image to Docker Hub
      - name: Push backend image to Docker Hub
        run: docker push srimathi2004/movie-backend:latest
